src/config/routes.rb
# frozen_string_literal: true

# This file tells the Rails server how incoming requests are sent to which
# controller and method.
#
#
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do
  resources :municipality_social_data do
    collection { post :import }
  end
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # The root page, e.g. www.example.com/, is sent here
  # root 'controller#method_in_controller'
  #root 'municipality_social_data#index'
  root 'home#index'
  # Devise authentification pages. This controlls the user login
  # and authentification system.
  devise_for :users

  # Examples:
  #
  # # Add app CRUD operations from a controller. Used with scaffolding.
  # # CRUD -> create (API/POST), new (page/GET), index, show,
  #           edit(page/GET), update(API/PATCH|PUT), destroy(API/DELETE)
  # resources :my_controller
  #
  # # Add GET path for photos controller, index method
  # get 'photos/index'
  
  get 'home/dashboard', to: 'home#dashboard', as: 'dashboard'
  get 'home/bar_graph', to: 'home#bar_graph', as: 'bar_graph'
  get 'home/chart_js2', to: 'home#chart_js2', as: 'chart_js2'
  get 'home/echarts', to: 'home#echarts', as: 'echarts'
  get 'home/moris_js', to: 'home#moris_js', as: 'moris_js'
  get 'home/other_charts', to: 'home#other_charts', as: 'other_charts'

  # # Resources, but only register these methods
  # resources :photos, only: [:index, :new, :create, :destroy]
  #
  # # Add PUT path for the given url, but send it to a different controller
  # # than rails would assume by the name. to: 'controller#method_name'.
  # # It would have extected to: 'add_tags#add', which would fail
  # put '/add_tags/add', to: 'users#add_tags'
end

src/app/controllers/municipality_social_data_controller.rb
class MunicipalitySocialDataController < ApplicationController
  before_action :set_municipality_social_datum, only: [:show, :edit, :update, :destroy]

  # GET /municipality_social_data
  # GET /municipality_social_data.json
  def index
    @municipality_social_data = MunicipalitySocialDatum.all
  end

  # GET /municipality_social_data/1
  # GET /municipality_social_data/1.json
  def show
  end

  # GET /municipality_social_data/new
  def new
    @municipality_social_datum = MunicipalitySocialDatum.new
  end

  # GET /municipality_social_data/1/edit
  def edit
  end

  # POST /municipality_social_data
  # POST /municipality_social_data.json
  def create
    @municipality_social_datum = MunicipalitySocialDatum.new(municipality_social_datum_params)

    respond_to do |format|
      if @municipality_social_datum.save
        format.html { redirect_to @municipality_social_datum, notice: 'Municipality social datum was successfully created.' }
        format.json { render :show, status: :created, location: @municipality_social_datum }
      else
        format.html { render :new }
        format.json { render json: @municipality_social_datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /municipality_social_data/1
  # PATCH/PUT /municipality_social_data/1.json
  def update
    respond_to do |format|
      if @municipality_social_datum.update(municipality_social_datum_params)
        format.html { redirect_to @municipality_social_datum, notice: 'Municipality social datum was successfully updated.' }
        format.json { render :show, status: :ok, location: @municipality_social_datum }
      else
        format.html { render :edit }
        format.json { render json: @municipality_social_datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /municipality_social_data/1
  # DELETE /municipality_social_data/1.json
  def destroy
    @municipality_social_datum.destroy
    respond_to do |format|
      format.html { redirect_to municipality_social_data_url, notice: 'Municipality social datum was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import
    MunicipalitySocialDatum.import(params[:file])
    redirect_to root_path, notice: "Social Data Imported!"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_municipality_social_datum
      @municipality_social_datum = MunicipalitySocialDatum.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def municipality_social_datum_params
      params.require(:municipality_social_datum).permit(:name, :year, :households, :family_households, :percent_family_households, :married_male_above_15, :never_married_male_above_15, :percent_never_married_males_above_15, :married_females_above_15, :never_married_females_above_15, :percent_never_married_females_above_15, :total_15to50_gave_birth_past_year, :older_3_in_school, :older_3_in_highschool, :percent_older_3_in_highschool, :older_3_in_college_or_graduate, :percent_older_3_in_college_or_graduate, :total_25_and_older_highschool_grad, :percent_25_and_older_highschool_grad, :household_with_computer, :percent_household_with_computer)
    end
end

src/app/helpers/municipality_social_data_helper.rb
module MunicipalitySocialDataHelper
end

src/app/views/municipality_social_data/_form.html.erb
<%= form_with(model: municipality_social_datum, local: true) do |form| %>
  <% if municipality_social_datum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(municipality_social_datum.errors.count, "error") %> prohibited this municipality_social_datum from being saved:</h2>

      <ul>
        <% municipality_social_datum.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.text_field :year %>
  </div>

  <div class="field">
    <%= form.label :households %>
    <%= form.number_field :households %>
  </div>

  <div class="field">
    <%= form.label :family_households %>
    <%= form.number_field :family_households %>
  </div>

  <div class="field">
    <%= form.label :percent_family_households %>
    <%= form.text_field :percent_family_households %>
  </div>

  <div class="field">
    <%= form.label :married_male_above_15 %>
    <%= form.number_field :married_male_above_15 %>
  </div>

  <div class="field">
    <%= form.label :never_married_male_above_15 %>
    <%= form.number_field :never_married_male_above_15 %>
  </div>

  <div class="field">
    <%= form.label :percent_never_married_males_above_15 %>
    <%= form.text_field :percent_never_married_males_above_15 %>
  </div>

  <div class="field">
    <%= form.label :married_females_above_15 %>
    <%= form.number_field :married_females_above_15 %>
  </div>

  <div class="field">
    <%= form.label :never_married_females_above_15 %>
    <%= form.number_field :never_married_females_above_15 %>
  </div>

  <div class="field">
    <%= form.label :percent_never_married_females_above_15 %>
    <%= form.text_field :percent_never_married_females_above_15 %>
  </div>

  <div class="field">
    <%= form.label :total_15to50_gave_birth_past_year %>
    <%= form.number_field :total_15to50_gave_birth_past_year %>
  </div>

  <div class="field">
    <%= form.label :older_3_in_school %>
    <%= form.number_field :older_3_in_school %>
  </div>

  <div class="field">
    <%= form.label :older_3_in_highschool %>
    <%= form.number_field :older_3_in_highschool %>
  </div>

  <div class="field">
    <%= form.label :percent_older_3_in_highschool %>
    <%= form.text_field :percent_older_3_in_highschool %>
  </div>

  <div class="field">
    <%= form.label :older_3_in_college_or_graduate %>
    <%= form.number_field :older_3_in_college_or_graduate %>
  </div>

  <div class="field">
    <%= form.label :percent_older_3_in_college_or_graduate %>
    <%= form.text_field :percent_older_3_in_college_or_graduate %>
  </div>

  <div class="field">
    <%= form.label :total_25_and_older_highschool_grad %>
    <%= form.number_field :total_25_and_older_highschool_grad %>
  </div>

  <div class="field">
    <%= form.label :percent_25_and_older_highschool_grad %>
    <%= form.text_field :percent_25_and_older_highschool_grad %>
  </div>

  <div class="field">
    <%= form.label :household_with_computer %>
    <%= form.number_field :household_with_computer %>
  </div>

  <div class="field">
    <%= form.label :percent_household_with_computer %>
    <%= form.text_field :percent_household_with_computer %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

src/app/views/municipality_social_data/edit.html.erb
<h1>Editing Municipality Social Datum</h1>

<%= render 'form', municipality_social_datum: @municipality_social_datum %>

<%= link_to 'Show', @municipality_social_datum %> |
<%= link_to 'Back', municipality_social_data_path %>

src/app/views/municipality_social_data/index.html.erb
<div class="right_col" role="main">
 
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>
                    Plain Page <small>Page subtile </small>
                </h3>
            </div>
 
            <div class="title_right">
                <div class="col-md-5 col-sm-5   form-group pull-right top_search">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Search for...">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="button">Go!</button>
                        </span>
                    </div>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
 
        <div class="row">
            <div class="col-md-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Page title <small>Page subtile </small></h2>
                        <ul class="nav navbar-right panel_toolbox">
                            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    <i class="fa fa-wrench"></i>
                                </a>
                                <ul class="dropdown-menu" role="menu">
                                    <li><a href="#">Settings 1</a></li>
                                    <li><a href="#">Settings 2</a></li>
                                </ul>
                            </li>
                            <li><a class="close-link"><i class="fa fa-close"></i></a></li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <!-- content starts here -->
                        <p id="notice"><%= notice %></p>

                        <h1>Municipality Social Data</h1>

                        <table>
                          <thead>
                            <tr>
                              <th>Name</th>
                              <th>Year</th>
                              <th>Households</th>
                              <th>Family households</th>
                              <th>Percent family households</th>
                              <th>Married male above 15</th>
                              <th>Never married male above 15</th>
                              <th>Percent never married males above 15</th>
                              <th>Married females above 15</th>
                              <th>Never married females above 15</th>
                              <th>Percent never married females above 15</th>
                              <th>Total 15to50 gave birth past year</th>
                              <th>Older 3 in school</th>
                              <th>Older 3 in highschool</th>
                              <th>Percent older 3 in highschool</th>
                              <th>Older 3 in college or graduate</th>
                              <th>Percent older 3 in college or graduate</th>
                              <th>Total 25 and older highschool grad</th>
                              <th>Percent 25 and older highschool grad</th>
                              <th>Household with computer</th>
                              <th>Percent household with computer</th>
                              <th colspan="3"></th>
                            </tr>
                          </thead>

                          <tbody>
                            <% @municipality_social_data.each do |municipality_social_datum| %>
                              <tr>
                                <td><%= municipality_social_datum.name %></td>
                                <td><%= municipality_social_datum.year %></td>
                                <td><%= municipality_social_datum.households %></td>
                                <td><%= municipality_social_datum.family_households %></td>
                                <td><%= municipality_social_datum.percent_family_households %></td>
                                <td><%= municipality_social_datum.married_male_above_15 %></td>
                                <td><%= municipality_social_datum.never_married_male_above_15 %></td>
                                <td><%= municipality_social_datum.percent_never_married_males_above_15 %></td>
                                <td><%= municipality_social_datum.married_females_above_15 %></td>
                                <td><%= municipality_social_datum.never_married_females_above_15 %></td>
                                <td><%= municipality_social_datum.percent_never_married_females_above_15 %></td>
                                <td><%= municipality_social_datum.total_15to50_gave_birth_past_year %></td>
                                <td><%= municipality_social_datum.older_3_in_school %></td>
                                <td><%= municipality_social_datum.older_3_in_highschool %></td>
                                <td><%= municipality_social_datum.percent_older_3_in_highschool %></td>
                                <td><%= municipality_social_datum.older_3_in_college_or_graduate %></td>
                                <td><%= municipality_social_datum.percent_older_3_in_college_or_graduate %></td>
                                <td><%= municipality_social_datum.total_25_and_older_highschool_grad %></td>
                                <td><%= municipality_social_datum.percent_25_and_older_highschool_grad %></td>
                                <td><%= municipality_social_datum.household_with_computer %></td>
                                <td><%= municipality_social_datum.percent_household_with_computer %></td>
                                <td><%= link_to 'Show', municipality_social_datum %></td>
                                <td><%= link_to 'Edit', edit_municipality_social_datum_path(municipality_social_datum) %></td>
                                <td><%= link_to 'Destroy', municipality_social_datum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                              </tr>
                            <% end %>
                          </tbody>
                        </table>

                        <br>

                        <%= link_to 'New Municipality Social Datum', new_municipality_social_datum_path %>

                        <br>

                        <h4> Import That Data </h4>
                        <%= form_tag import_municipality_social_data_path, multipart:true do %>
                          <%= file_field_tag :file %>
                          <%= submit_tag "Import CSV" %>
                        <% end %>
                        <!-- content ends here -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

src/app/views/municipality_social_data/new.html.erb
<h1>New Municipality Social Datum</h1>

<%= render 'form', municipality_social_datum: @municipality_social_datum %>

<%= link_to 'Back', municipality_social_data_path %>

src/app/views/municipality_social_data/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @municipality_social_datum.name %>
</p>

<p>
  <strong>Year:</strong>
  <%= @municipality_social_datum.year %>
</p>

<p>
  <strong>Households:</strong>
  <%= @municipality_social_datum.households %>
</p>

<p>
  <strong>Family households:</strong>
  <%= @municipality_social_datum.family_households %>
</p>

<p>
  <strong>Percent family households:</strong>
  <%= @municipality_social_datum.percent_family_households %>
</p>

<p>
  <strong>Married male above 15:</strong>
  <%= @municipality_social_datum.married_male_above_15 %>
</p>

<p>
  <strong>Never married male above 15:</strong>
  <%= @municipality_social_datum.never_married_male_above_15 %>
</p>

<p>
  <strong>Percent never married males above 15:</strong>
  <%= @municipality_social_datum.percent_never_married_males_above_15 %>
</p>

<p>
  <strong>Married females above 15:</strong>
  <%= @municipality_social_datum.married_females_above_15 %>
</p>

<p>
  <strong>Never married females above 15:</strong>
  <%= @municipality_social_datum.never_married_females_above_15 %>
</p>

<p>
  <strong>Percent never married females above 15:</strong>
  <%= @municipality_social_datum.percent_never_married_females_above_15 %>
</p>

<p>
  <strong>Total 15to50 gave birth past year:</strong>
  <%= @municipality_social_datum.total_15to50_gave_birth_past_year %>
</p>

<p>
  <strong>Older 3 in school:</strong>
  <%= @municipality_social_datum.older_3_in_school %>
</p>

<p>
  <strong>Older 3 in highschool:</strong>
  <%= @municipality_social_datum.older_3_in_highschool %>
</p>

<p>
  <strong>Percent older 3 in highschool:</strong>
  <%= @municipality_social_datum.percent_older_3_in_highschool %>
</p>

<p>
  <strong>Older 3 in college or graduate:</strong>
  <%= @municipality_social_datum.older_3_in_college_or_graduate %>
</p>

<p>
  <strong>Percent older 3 in college or graduate:</strong>
  <%= @municipality_social_datum.percent_older_3_in_college_or_graduate %>
</p>

<p>
  <strong>Total 25 and older highschool grad:</strong>
  <%= @municipality_social_datum.total_25_and_older_highschool_grad %>
</p>

<p>
  <strong>Percent 25 and older highschool grad:</strong>
  <%= @municipality_social_datum.percent_25_and_older_highschool_grad %>
</p>

<p>
  <strong>Household with computer:</strong>
  <%= @municipality_social_datum.household_with_computer %>
</p>

<p>
  <strong>Percent household with computer:</strong>
  <%= @municipality_social_datum.percent_household_with_computer %>
</p>

<%= link_to 'Edit', edit_municipality_social_datum_path(@municipality_social_datum) %> |
<%= link_to 'Back', municipality_social_data_path %>