src/config/routes.rb
# frozen_string_literal: true

# This file tells the Rails server how incoming requests are sent to which
# controller and method.
#
#
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do
  resources :municipality_social_data do
    collection { post :import }
  end
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # The root page, e.g. www.example.com/, is sent here
  # root 'controller#method_in_controller'
  #root 'municipality_social_data#index'
  root 'home#index'
  # Devise authentification pages. This controlls the user login
  # and authentification system.
  devise_for :users

  # Examples:
  #
  # # Add app CRUD operations from a controller. Used with scaffolding.
  # # CRUD -> create (API/POST), new (page/GET), index, show,
  #           edit(page/GET), update(API/PATCH|PUT), destroy(API/DELETE)
  # resources :my_controller
  #
  # # Add GET path for photos controller, index method
  # get 'photos/index'
  
  get 'home/dashboard', to: 'home#dashboard', as: 'dashboard'
  get 'home/bar_graph', to: 'home#bar_graph', as: 'bar_graph'
  get 'home/chart_js2', to: 'home#chart_js2', as: 'chart_js2'
  get 'home/echarts', to: 'home#echarts', as: 'echarts'
  get 'home/moris_js', to: 'home#moris_js', as: 'moris_js'
  get 'home/other_charts', to: 'home#other_charts', as: 'other_charts'

  # # Resources, but only register these methods
  # resources :photos, only: [:index, :new, :create, :destroy]
  #
  # # Add PUT path for the given url, but send it to a different controller
  # # than rails would assume by the name. to: 'controller#method_name'.
  # # It would have extected to: 'add_tags#add', which would fail
  # put '/add_tags/add', to: 'users#add_tags'
end

src/app/views/partials/_css.html.erb
<link href="https://colorlib.com/polygon/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">

<link href="https://colorlib.com/polygon/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">

<link href="https://colorlib.com/polygon/vendors/nprogress/nprogress.css" rel="stylesheet">

<link href="https://colorlib.com/polygon/vendors/iCheck/skins/flat/green.css" rel="stylesheet">

<link href="https://colorlib.com/polygon/vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css" rel="stylesheet">

<link href="https://colorlib.com/polygon/vendors/jqvmap/dist/jqvmap.min.css" rel="stylesheet" />

<link href="https://colorlib.com/polygon/vendors/bootstrap-daterangepicker/daterangepicker.css" rel="stylesheet">

<link href="https://colorlib.com/polygon/build/css/custom.min.css" rel="stylesheet">

src/app/views/partials/_footer.html.erb
<footer>
  <div class="pull-right">
    Gentelella - Bootstrap Admin Template by <a href="https://colorlib.com">Colorlib</a>
  </div>
  <div class="clearfix"></div>
</footer>

src/app/views/partials/_javascript.html.erb
<script src="https://colorlib.com/polygon/vendors/jquery/dist/jquery.min.js" type="ad820bc8304ed946f67eacb7-text/javascript"></script>

<script src="https://colorlib.com/polygon/vendors/bootstrap/dist/js/bootstrap.bundle.min.js" type="ad820bc8304ed946f67eacb7-text/javascript"></script>

<script src="https://colorlib.com/polygon/vendors/fastclick/lib/fastclick.js" type="ad820bc8304ed946f67eacb7-text/javascript"></script>

<script src="https://colorlib.com/polygon/vendors/nprogress/nprogress.js" type="ad820bc8304ed946f67eacb7-text/javascript"></script>

<script src="https://colorlib.com/polygon/vendors/Chart.js/dist/Chart.min.js" type="ad820bc8304ed946f67eacb7-text/javascript"></script>

<script src="https://colorlib.com/polygon/vendors/gauge.js/dist/gauge.min.js" type="ad820bc8304ed946f67eacb7-text/javascript"></script>

<script src="https://colorlib.com/polygon/vendors/bootstrap-progressbar/bootstrap-progressbar.min.js" type="ad820bc8304ed946f67eacb7-text/javascript"></script>

<script src="https://colorlib.com/polygon/vendors/iCheck/icheck.min.js" type="ad820bc8304ed946f67eacb7-text/javascript"></script>

<script src="https://colorlib.com/polygon/vendors/skycons/skycons.js" type="ad820bc8304ed946f67eacb7-text/javascript"></script>

<script src="https://colorlib.com/polygon/vendors/Flot/jquery.flot.js" type="ad820bc8304ed946f67eacb7-text/javascript"></script>
<script src="https://colorlib.com/polygon/vendors/Flot/jquery.flot.pie.js" type="ad820bc8304ed946f67eacb7-text/javascript"></script>
<script src="https://colorlib.com/polygon/vendors/Flot/jquery.flot.time.js" type="ad820bc8304ed946f67eacb7-text/javascript"></script>
<script src="https://colorlib.com/polygon/vendors/Flot/jquery.flot.stack.js" type="ad820bc8304ed946f67eacb7-text/javascript"></script>
<script src="https://colorlib.com/polygon/vendors/Flot/jquery.flot.resize.js" type="ad820bc8304ed946f67eacb7-text/javascript"></script>

<script src="https://colorlib.com/polygon/vendors/flot.orderbars/js/jquery.flot.orderBars.js" type="ad820bc8304ed946f67eacb7-text/javascript"></script>
<script src="https://colorlib.com/polygon/vendors/flot-spline/js/jquery.flot.spline.min.js" type="ad820bc8304ed946f67eacb7-text/javascript"></script>
<script src="https://colorlib.com/polygon/vendors/flot.curvedlines/curvedLines.js" type="ad820bc8304ed946f67eacb7-text/javascript"></script>

<script src="https://colorlib.com/polygon/vendors/DateJS/build/date.js" type="ad820bc8304ed946f67eacb7-text/javascript"></script>

<script src="https://colorlib.com/polygon/vendors/jqvmap/dist/jquery.vmap.js" type="ad820bc8304ed946f67eacb7-text/javascript"></script>
<script src="https://colorlib.com/polygon/vendors/jqvmap/dist/maps/jquery.vmap.world.js" type="ad820bc8304ed946f67eacb7-text/javascript"></script>
<script src="https://colorlib.com/polygon/vendors/jqvmap/examples/js/jquery.vmap.sampledata.js" type="ad820bc8304ed946f67eacb7-text/javascript"></script>

<script src="https://colorlib.com/polygon/vendors/moment/min/moment.min.js" type="ad820bc8304ed946f67eacb7-text/javascript"></script>
<script src="https://colorlib.com/polygon/vendors/bootstrap-daterangepicker/daterangepicker.js" type="ad820bc8304ed946f67eacb7-text/javascript"></script>

<script src="https://colorlib.com/polygon/build/js/custom.min.js" type="ad820bc8304ed946f67eacb7-text/javascript"></script>
<script src="https://ajax.cloudflare.com/cdn-cgi/scripts/7089c43e/cloudflare-static/rocket-loader.min.js" data-cf-settings="ad820bc8304ed946f67eacb7-|49" defer=""></script></body>

src/app/views/partials/_sidenav.html.erb
<div class="col-md-3 left_col">
<div class="left_col scroll-view">
<div class="navbar nav_title" style="border: 0;">
<a href= "/" class="site_title"><i class="fa fa-area-chart"></i> <span>ConCensus</span></a>
</div>
<div class="clearfix"></div>

<div class="profile clearfix">
<div class="profile_pic">
<% image_tag "img.jpg", :alt => "..." %>
</div>
<div class="profile_info">
<span>Welcome</span>
</div>
</div>

<br>

<div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
    <div class="menu_section active">
        <h3>General</h3>
        <ul class="nav side-menu" style="">
            <li class=""><a><i class="fa fa-home"></i> Home <span class="fa fa-chevron-down"></span></a>
                <ul class="nav child_menu" style="display: none;">
                    <li class="current-page"><%= link_to 'Line Graph', dashboard_path,  data: { turbolinks: false } %></li>
                    <li class="current-page"><%= link_to 'Bar Graph', bar_graph_path,  data: { turbolinks: false } %></li>
                </ul>
            </li>
        </ul>
    </div>
</div>

<div class="sidebar-footer hidden-small">
<a data-toggle="tooltip" data-placement="top" title="" data-original-title="Settings">
<span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
</a>
<a data-toggle="tooltip" data-placement="top" title="" data-original-title="FullScreen">
<span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
</a>
<a data-toggle="tooltip" data-placement="top" title="" data-original-title="Lock">
<span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
</a>
<%= link_to '<span class="glyphicon glyphicon-off" aria-hidden="true"></span>'.html_safe, new_user_session_path, { :class => 'tooltips', 'data-toggle' => 'tooltip', 'data-placement' => 'top', :title => '', 'data-original-title' => 'Login' } %>
</a>
</div>

</div>
</div>

src/app/views/partials/_topnav.html.erb
<div class="top_nav">
<div class="nav_menu">
<div class="nav toggle">
<a id="menu_toggle"><i class="fa fa-bars"></i></a>
</div>
<nav class="nav navbar-nav">
<ul class=" navbar-right">
<% if user_signed_in? %>
<li class="nav-item dropdown open" style="padding-left: 15px;">
<a href="javascript:;" class="user-profile dropdown-toggle" aria-haspopup="true" id="navbarDropdown" data-toggle="dropdown" aria-expanded="false">
<% image_tag "img.jpg", :alt => "" %>Account
</a>
<div class="dropdown-menu dropdown-usermenu pull-right" aria-labelledby="navbarDropdown">
<a class="dropdown-item" href="javascript:;"> Profile</a>
<a class="dropdown-item" href="javascript:;">
<span class="badge bg-red pull-right">50%</span>
<span>Settings</span>
</a>
<a class="dropdown-item" href="javascript:;">Help</a>
<%= link_to "Log Out", destroy_user_session_path, class: "dropdown-item", method: :delete %>
</div>
<% else %>
<li class="nav-item dropdown open" style="padding-left: 15px;">
<a href="javascript:;" class="user-profile dropdown-toggle" aria-haspopup="true" id="navbarDropdown" data-toggle="dropdown" aria-expanded="false">
<img src="images/img.jpg" alt="">Want to save your work?
</a>
<div class="dropdown-menu dropdown-usermenu pull-right" aria-labelledby="navbarDropdown">
<%= link_to "Register", new_user_registration_path, class: "dropdown-item" %>
<%= link_to "Log In", new_user_session_path, class: "dropdown-item" %>
</div>
<% end %>
</li>
</ul>
</nav>
</div>
</div>